#!/usr/bin/env ruby

require_relative 'sources/game'

def main
    black_jack = Game.new :money => 10000, :nb_deck => 6
    while !black_jack.end?
        black_jack.deal
        black_jack.play
    end
end

main
