#!/usr/bin/env ruby

require_relative "sources/game"

def main
    round = 0
    black_jack = Game.new :money => 10000, :nb_deck => 6
    while !black_jack.end?
        puts "=== ROUND === #{ round }"
        black_jack.deal
        black_jack.play
        round += 1
    end
end

# begin
main
# rescue Exception => error
#     puts error.message
#
# end
